"""Local HTTP server backing the map selector GUI.

The interactive front-end (``static/editor.html``) runs in the browser against
live OSM tiles; this server is the thin native half that lists existing
scenarios and writes new ones. Keeping the I/O here (rather than in the page)
means scenario YAML is produced by the same validated :class:`ScenarioConfig`
the CLI uses, so the GUI can never emit a package the pipeline would reject.

The HTTP surface is intentionally tiny:

    GET  /                  the editor page
    GET  /api/scenarios     existing scenarios in the target dir (as bboxes)
    POST /api/scenario      validate + write one scenario YAML
"""

from __future__ import annotations

import json
import logging
import re
import threading
import webbrowser
from dataclasses import replace
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from importlib import resources
from pathlib import Path

from ..config import BBox, ScenarioConfig

log = logging.getLogger(__name__)

_SLUG_RE = re.compile(r"[^a-z0-9]+")


def slugify(name: str) -> str:
    """Turn a scenario name into a safe kebab-case file stem."""
    slug = _SLUG_RE.sub("-", name.strip().lower()).strip("-")
    return slug or "scenario"


def scenario_yaml(config: ScenarioConfig) -> str:
    """Render a :class:`ScenarioConfig` as a scenario YAML document.

    Hand-templated (rather than ``yaml.dump``) to match the style of the
    bundled scenarios — a header comment and an inline ``bbox`` list.
    """
    b = config.bbox
    return (
        f"# {config.name} — generated by the Krieg map selector.\n"
        f"name: {config.name}\n"
        f"bbox: [{b.min_lon:g}, {b.min_lat:g}, {b.max_lon:g}, {b.max_lat:g}]\n"
        f"target_year: {config.target_year}\n"
        f"contour_interval_m: {config.contour_interval_m:g}\n"
        f"cluster_buildings: {str(config.cluster_buildings).lower()}\n"
    )


def config_from_request(payload: dict) -> ScenarioConfig:
    """Build (and thereby validate) a :class:`ScenarioConfig` from JSON.

    Raises ``ValueError`` / ``KeyError`` on bad input; the handler turns those
    into a 400 so the browser can show the message.
    """
    bbox_in = payload["bbox"]
    bbox = BBox(*(float(v) for v in bbox_in))
    return ScenarioConfig(
        name=str(payload.get("name") or "untitled").strip(),
        bbox=bbox,
        target_year=int(payload.get("target_year", 1880)),
        contour_interval_m=float(payload.get("contour_interval_m", 10.0)),
        cluster_buildings=bool(payload.get("cluster_buildings", True)),
    )


def save_scenario(scenarios_dir: Path, config: ScenarioConfig, *, overwrite: bool) -> Path:
    """Write the scenario YAML, returning its path.

    Without ``overwrite`` an existing file is preserved and a numeric suffix is
    appended so a careless save never clobbers prior work.
    """
    scenarios_dir.mkdir(parents=True, exist_ok=True)
    stem = slugify(config.name)
    path = scenarios_dir / f"{stem}.yaml"
    if not overwrite:
        n = 2
        while path.exists():
            path = scenarios_dir / f"{stem}-{n}.yaml"
            n += 1
    path.write_text(scenario_yaml(config))
    return path


def list_scenarios(scenarios_dir: Path) -> list[dict]:
    """Existing scenarios in the dir, as GUI-ready dicts (name + bbox + knobs).

    Unreadable files are skipped rather than failing the whole listing.
    """
    out: list[dict] = []
    for path in sorted(scenarios_dir.glob("*.yaml")):
        try:
            config = ScenarioConfig.from_yaml(path)
        except Exception as exc:  # noqa: BLE001 — a bad file shouldn't break the list
            log.warning("skipping %s: %s", path.name, exc)
            continue
        out.append(
            {
                "file": path.name,
                "name": config.name,
                "bbox": list(config.bbox.as_tuple()),
                "target_year": config.target_year,
                "contour_interval_m": config.contour_interval_m,
                "cluster_buildings": config.cluster_buildings,
            }
        )
    return out


def _load_page() -> bytes:
    return (resources.files(__package__) / "static" / "editor.html").read_bytes()


def make_handler(scenarios_dir: Path) -> type[BaseHTTPRequestHandler]:
    """Build a request handler bound to ``scenarios_dir``."""

    class Handler(BaseHTTPRequestHandler):
        server_version = "KriegMapSelector/0.1"

        def log_message(self, fmt: str, *args) -> None:  # quieter than default
            log.debug("%s - %s", self.address_string(), fmt % args)

        def _send_json(self, status: int, body: dict) -> None:
            data = json.dumps(body).encode()
            self.send_response(status)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(data)))
            self.end_headers()
            self.wfile.write(data)

        def do_GET(self) -> None:  # noqa: N802 — stdlib naming
            if self.path in ("/", "/index.html"):
                page = _load_page()
                self.send_response(200)
                self.send_header("Content-Type", "text/html; charset=utf-8")
                self.send_header("Content-Length", str(len(page)))
                self.end_headers()
                self.wfile.write(page)
            elif self.path == "/api/scenarios":
                self._send_json(200, {"scenarios": list_scenarios(scenarios_dir)})
            else:
                self._send_json(404, {"error": "not found"})

        def do_POST(self) -> None:  # noqa: N802
            if self.path != "/api/scenario":
                self._send_json(404, {"error": "not found"})
                return
            length = int(self.headers.get("Content-Length", 0))
            try:
                payload = json.loads(self.rfile.read(length) or b"{}")
                config = config_from_request(payload)
            except (ValueError, KeyError, TypeError, json.JSONDecodeError) as exc:
                self._send_json(400, {"error": str(exc)})
                return
            path = save_scenario(
                scenarios_dir, config, overwrite=bool(payload.get("overwrite"))
            )
            build_cmd = f"krieg-pipeline build --scenario {path} --out out/{path.stem} --preview"
            log.info("wrote %s", path)
            self._send_json(200, {"file": path.name, "path": str(path), "build_cmd": build_cmd})

    return Handler


def serve(
    scenarios_dir: Path,
    *,
    host: str = "127.0.0.1",
    port: int = 8682,
    open_browser: bool = True,
) -> None:
    """Run the selector until interrupted (Ctrl-C)."""
    scenarios_dir = Path(scenarios_dir)
    httpd = ThreadingHTTPServer((host, port), make_handler(scenarios_dir))
    url = f"http://{host}:{port}/"
    log.info("Map selector on %s  (scenarios → %s)", url, scenarios_dir)
    print(f"\n  Krieg map selector → {url}")
    print(f"  Saving scenarios to {scenarios_dir}")
    print("  Press Ctrl-C to stop.\n")
    if open_browser:
        threading.Timer(0.5, lambda: webbrowser.open(url)).start()
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        print("\n  stopped.")
    finally:
        httpd.server_close()
